//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIRS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentId { get; set; }
        public int UserId { get; set; }
        public string Comments { get; set; }
        public System.DateTime Created { get; set; }
        public int OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
