//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIRS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int OrderId { get; set; }
        public int ApplicantUserId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> DepartmentUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> RecievedDate { get; set; }
        public Nullable<System.DateTime> SendToDepartmentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
    }
}
